services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: janapesequotes
    depends_on:
      - db
    environment:
      - POSTGRES_USER=globin
      - POSTGRES_PASSWORD=globin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/janapesedb
      - SPRING_DATASOURCE_USERNAME=globin
      - SPRING_DATASOURCE_PASSWORD=globin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: janapesedb
    environment:
      - POSTGRES_USER=globin
      - POSTGRES_PASSWORD=globin
      - POSTGRES_DB=janapesedb
    ports:
      - "5432:5432"